name: Build yarn

on: [push]

jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
        - name: Use Node.js
          uses: actions/setup-node@v3
        - run: |
            yarn install
            yarn build
